#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''
  
  # --- Identity Setup ---
  identity:
    hostname: otsig-dev-machine
    username: otsig
    password: $6$2GUgumUxFS0gVZs0$JHL00IeKsYHHgw.784mOGSLncp6k7a2snVulWd2i/oTlrzr065QdO38jr.WHqVerLBYmz6ifM8lnw5NmbitPz1
  # --- Storage (Automatically use the entire disk) ---
  storage:
    layout:
      name: automatic
      match: {}
  
  # --- Packages to Install (Cleaned up list) ---
  packages:
    - docker.io
    - openssh-server
    - git
    - python3
    - wireshark
    # Packages needed for robustness/dependencies
    - software-properties-common 
    - apt-transport-https

  # --- Shell Commands (Only VS Code) ---
  late-commands:
    # 1. Install VS Code via SNAP using the 'edge' channel for ARM64 availability.
    # The '|| true' ensures that if the snap install fails, the overall autoinstall script continues.
    - 'curtin in-target --target=/target -- sh -c "snap install code --classic --channel=edge || true"'
    
  # --- User-Data Section for Post-Creation Setup ---
  # This section runs via cloud-init *after* the 'otsig' user is guaranteed to exist.
  user-data:
    runcmd:
      # 1. Add otsig to the docker group
      - usermod -aG docker otsig
      
      # 2. Simplified .bashrc modification (single line append)
      - sh -c "echo -e \"\n# Custom welcome message\necho \"Welcome to the custom otsig dev environment!\"\" >> /home/otsig/.bashrc"
      
      # 3. Ensure correct ownership of the new .bashrc file
      - chown otsig:otsig /home/otsig/.bashrc

  # --- Reboot Command ---
  # Ensures the system reboots cleanly after installation is finalized
  power-state:
    delay: 0
    mode: reboot
    timeout: 30

