#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''
  
  # --- Identity Setup ---
  identity:
    hostname: otsig-dev-machine
    username: otsig
    password: "$6$2GUgumUxFS0gVZs0$JHL00IeKsYHHgw.784mOGSLncp6k7a2snVulWd2i/oTlrzr065QdO38jr.WHqVerLBYmz6ifM8lnw5NmbitPz1"

  # --- Storage (Automatically use the entire disk) ---
  storage:
    layout:
      name: automatic
      match: {}
  
  # --- Packages to Install ---
  packages:
    - docker.io
    - openssh-server
    - git
    - python3
    - wireshark
    - wget
    - gpg
    - software-properties-common
    - apt-transport-https # Needed for external repo setup

  # --- Shell Commands (Including VS Code Setup and .bashrc) ---
  late-commands:
    # 1. Install VS Code Repository Key and Source
    - 'wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | curtin in-target --target=/target -- tee /usr/share/keyrings/packages.microsoft.gpg > /dev/null'
    - 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | curtin in-target --target=/target -- tee /etc/apt/sources.list.d/vscode.list > /dev/null'
    
    # 2. Install the 'code' package
    - 'curtin in-target --target=/target -- apt update'
    - 'curtin in-target --target=/target -- apt install -y code'
    
    # 3. Add otsig to the docker group (must be done post-install)
    - 'curtin in-target --target=/target -- usermod -aG docker otsig'
