#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''
  
  # --- Identity Setup ---
  identity:
    hostname: otsig-dev-machine
    username: otsig
    password: $6$2GUgumUxFS0gVZs0$JHL00IeKsYHHgw.784mOGSLncp6k7a2snVulWd2i/oTlrzr065QdO38jr.WHqVerLBYmz6ifM8lnw5NmbitPz1
  # --- Storage (Automatically use the entire disk) ---
  storage:
    layout:
      name: automatic
      match: {}
  
  # --- Packages to Install (Cleaned up list) ---
  packages:
    - docker.io
    - openssh-server
    - git
    - python3
    - wireshark
    # No longer need APT setup tools (curl, wget, gpg)
    - software-properties-common 
    - apt-transport-https

  # --- Shell Commands (Including VS Code Setup via SNAP) ---
  late-commands:
    # 1. Install VS Code via SNAP (Works reliably on ARM64/AArch64 systems)
    # The --classic flag is needed for VS Code to access system files.
    - 'curtin in-target --target=/target -- snap install code --classic'
    
    # 2. Add otsig to the docker group
    - 'curtin in-target --target=/target -- usermod -aG docker otsig'
    
    # 3. Simplified .bashrc modification (single line append)
    - 'curtin in-target --target=/target -- sh -c "echo -e \"\\n# Custom welcome message\\necho \\\"Welcome to the custom otsig dev environment!\\\"\" >> /home/otsig/.bashrc"'
    
    # 4. Ensure correct ownership of the new .bashrc file
    - 'curtin in-target --target=/target -- chown otsig:otsig /home/otsig/.bashrc'

